general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:    
    deployTool: 'cf_native'
    deployType: 'standard'
    cloudFoundry:
      org: '66de7174trial'
      space: 'dev'
      credentialsId: 'BTP-JIAROA'
      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com/'